version: '3'
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        command: npm run start
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production

    nginx:
        ports:
            - '80:80'
