version: '3'
services:
    node-app:
        build: .
        environment:
            - PORT=3000
        depends_on:
            - mongo

    mongo:
        image: mongo
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
    mongo-db:
    redis:
