version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        command: npm run start
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}

    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    nginx:
        ports:
            - "80:80"
