version: "3"
services:
  node-app:
    build: .
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dangnh
      - MONGO_INITDB_ROOT_PASSWORD=dangnhpass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
